

export const HOME_INCREASE = 'HOME_INCREASE';
export const HOME_DECREASE = 'HOME_DECREASE';
export const HOME_LOADING = 'HOME_LOADING';
export const HOME_LOAD_DATA_SUCCESS = 'HOME_LOAD_DATA_SUCCESS';
export const HOME_LOAD_DATA_FAIL = 'HOME_LOAD_DATA_FAIL';



export const LOGIN_CHECK_LOGIN_OR_REGISTER = 'LOGIN_CHECK_LOGIN_OR_REGISTER';
export const LOGIN_LOGIN_SUCCESS = 'LOGIN_LOGIN';
export const LOGIN_REGISTER_SUCCESS = 'LOGIN_REGISTER';